plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.144'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

repositories {
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.ithundxr.dev/snapshots" }
    maven { url = "https://modmaven.dev" }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    compileOnly project(':')
    compileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    compileOnly("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    compileOnly("com.tterrag.registrate:Registrate:${registrate_version}")
    compileOnly("mekanism:Mekanism:${mekanism_version}:api")
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version             : minecraft_version,
            minecraft_version_range       : minecraft_version_range,
            neo_version                   : neo_version,
            neo_version_range             : neo_version_range,
            loader_version_range          : loader_version_range,
            mod_id                        : mod_id,
            mod_name                      : mod_name,
            mod_version                   : mod_version,
            mod_license                   : mod_license,
            mod_authors                   : mod_authors,
            mod_description              : mod_description,
            create_nested_factory_version : rootProject.mod_version,
            mekanism_version_range        : '[10.7.0,)',
    ]
    inputs.properties replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
    expand replaceProperties
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata


// This module is bundled into the root mod; do not publish a standalone compat jar.
tasks.named('jar', Jar) {
    enabled = false
}
