mod_id=create_nested_factory_logistics
mod_name=Create Nested Factory Logistics Compatibility
mod_description=Integrates create_nested_factory with Pipez and Mekanism transport capabilities.
mod_version=1.5.0
mod_license=All Rights Reserved
mod_authors=Kevin_Dish1231

mekanism_version=1.21.1-10.7.7.64







